Add documentation to the repo
BHoM/MachineLearning_Toolkit pull request #48
Opened 2020-08-28 09:21 UTC by epignatelli

### Issues addressed by this PR

Closes #25
Closes #30

### Test files

### Changelog

- Add documentation about installation procedure
- Add documentation on how to add another algorithm

### Additional comments

2020-08-28 14:36 UTC, BingWangUS approved these changes

2020-08-28 14:40 UTC, BingWangUS requested changes

2020-08-28 14:40 UTC, BingWangUS commented on README.md
> +   the `BH.Engine.Python.Compute.InstallMachineLearningToolkit` component
`BH.Engine.MachineLearning.Compute.InstallMachineLearningToolkit`

2020-08-28 14:40 UTC, BingWangUS commented on README.md
> +Note that the intallation will take a while - around 15 minutes.
typo - installation

2020-09-02 10:15 UTC, epignatelli commented on README.md
> +   the `BH.Engine.Python.Compute.InstallMachineLearningToolkit` component
```suggestion
   the `BH.Engine.MachineLearning.Compute.InstallMachineLearningToolkit` component
```

2020-09-02 10:15 UTC, epignatelli commented on README.md
> +Note that the intallation will take a while - around 15 minutes.
```suggestion
Note that the installation will take a while - around 15 minutes.
```

2020-09-02 11:51 UTC, BingWangUS approved these changes

2020-09-02 13:50 UTC, merged