Add Linear Regression algorithm
BHoM/MachineLearning_Toolkit pull request #8
Opened 2020-04-16 16:00 UTC by epignatelli

### Issues addressed by this PR

Closes #5 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EmYIW2WfjUtPkIYccZ-8V8gBZTOmUfLfgK1gllazCEilcQ?e=C174yT

### Changelog

- Add Linear Regression algorithm
- Refactor the way modules are loaded
- Make sure that the `Invoke` method is always passing Python arguments

2020-04-16 20:11 UTC, epignatelli commented
@MarthaVoul @FraserGreenroyd FYI, this can be an example of code development workflow for adding an ML algorithm!

2020-04-17 11:55 UTC, FraserGreenroyd requested changes

2020-04-17 11:55 UTC, FraserGreenroyd commented on MachineLearning_Engine/MachineLearning_Engine.csproj
> +    </Reference>
Reference should not have version, culture, or processorArchitecture.
Should also be set to copy local false :smile:

2020-04-17 16:08 UTC, BingWangUS submitted a review, later dismissed
Function wise working great!

2020-04-17 16:10 UTC, BingWangUS commented
Would like to see an example to see how to structure a data structure in grasshopper for multi-input, x1, x2, x3. 

Also want to have the capacity to expose index from the model.

2020-04-17 16:33 UTC, FraserGreenroyd approved these changes

2020-04-17 17:07 UTC, merged

2020-04-17 21:49 UTC, al-fisher commented
> fix installation of ML_Tooltki python side

👍👍 thanks @epignatelli